name: DevSecOps Pipeline

on: [push, pull_request]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Crear carpeta de salida
        run: mkdir -p ${{ github.workspace }}/reports && chmod -R 777 ${{ github.workspace }}/reports

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1

      - name: Update Dependency-Check Database
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/dependency-check:/usr/share/dependency-check/data \
            owasp/dependency-check --updateonly
      
      - name: Run OWASP Dependency Check
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            -v ${{ github.workspace }}/reports:/reports \
            owasp/dependency-check \
            --scan /src \
            --format HTML \
            --out /reports \
            --disableRetireJS \
            --nvdApiKey ${{ secrets.NVD_API_KEY }}

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ${{ github.workspace }}/reports
      
      - name: Run Gitleaks for secret scanning
        uses: zricethezav/gitleaks-action@v1.6.0

      - name: Run OWASP ZAP Scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw \
            owasp/zap2docker-stable zap-full-scan.py -t http://localhost:3000 -r zap_report.html || true

      - name: Convert ZAP report to JSON
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw \
            owasp/zap2docker-stable zap-json-report.py -f zap_report.html -o zap_report.json || true

      - name: Upload ZAP Results to DefectDojo
        run: |
          curl -X POST "http://$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
            -H "Content-Type: application/json" \
            -F "scan_type=ZAP Scan" \
            -F "engagement=$ENGAGEMENT_ID" \
            -F "file=@zap_report.json"